# Generated by Django 6.0.1 on 2026-01-30 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='종목명')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='종목코드')),
            ],
        ),
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('open_price', models.IntegerField(verbose_name='시가')),
                ('high_price', models.IntegerField(verbose_name='고가')),
                ('low_price', models.IntegerField(verbose_name='저가')),
                ('close_price', models.IntegerField(verbose_name='종가')),
                ('volume', models.BigIntegerField(verbose_name='거래량')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stocks.stock')),
            ],
            options={
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
