# Generated by Django 6.0.1 on 2026-02-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="ai_decision",
            field=models.CharField(
                default="HOLD", max_length=10, verbose_name="AI추천"
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="ai_score",
            field=models.IntegerField(default=0, verbose_name="AI점수"),
        ),
        migrations.AddField(
            model_name="stock",
            name="current_price",
            field=models.IntegerField(blank=True, null=True, verbose_name="현재가"),
        ),
        migrations.AddField(
            model_name="stock",
            name="last_analyzed",
            field=models.DateTimeField(blank=True, null=True, verbose_name="분석시간"),
        ),
        migrations.AddField(
            model_name="stock",
            name="market",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="시장구분"
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="price_change",
            field=models.FloatField(blank=True, null=True, verbose_name="등락률"),
        ),
        migrations.AddField(
            model_name="stock",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="volume_change",
            field=models.FloatField(blank=True, null=True, verbose_name="거래량변동률"),
        ),
    ]
