# Generated by Django 6.0.1 on 2026-02-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "stocks",
            "0002_stock_ai_decision_stock_ai_score_stock_current_price_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="is_w_pattern",
            field=models.BooleanField(default=False, verbose_name="W패턴여부"),
        ),
        migrations.AddField(
            model_name="stock",
            name="w_score",
            field=models.IntegerField(default=0, verbose_name="W패턴점수"),
        ),
    ]
