# Generated by Django 6.0.1 on 2026-02-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0003_stock_is_w_pattern_stock_w_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyprice",
            name="ma20",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyprice",
            name="ma5",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyprice",
            name="ma60",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailyprice",
            name="rsi",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
