# Generated by Django 6.0.1 on 2026-02-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0004_dailyprice_ma20_dailyprice_ma5_dailyprice_ma60_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="ai_decision",
            field=models.CharField(
                default="HOLD", max_length=20, verbose_name="AI추천"
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="code",
            field=models.CharField(max_length=20, unique=True, verbose_name="종목코드"),
        ),
        migrations.AlterField(
            model_name="stock",
            name="market",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="시장구분"
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="name",
            field=models.CharField(max_length=100, verbose_name="종목명"),
        ),
    ]
